.TH "/home/speike/VSLAM/MSCKF_vio_ws/src/MSCKF_comments/include/msckf_vio/image_processor_nodelet.h" 3 "2024年 五月 9日 星期四" "S-MSCKF注释" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/speike/VSLAM/MSCKF_vio_ws/src/MSCKF_comments/include/msckf_vio/image_processor_nodelet.h
.SH SYNOPSIS
.br
.PP
\fC#include <nodelet/nodelet\&.h>\fP
.br
\fC#include <pluginlib/class_list_macros\&.h>\fP
.br
\fC#include <msckf_vio/image_processor\&.h>\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBmsckf_vio::ImageProcessorNodelet\fP"
.br
.RI "\fBImageProcessorNodelet\fP 继承自ros中的Nodelet类 Nodelet类是ROS中的一种插件类，可以在一个节点中运行多个Nodelet插件, 但是实际运行时 看起来就像是多个节点在运行。Nodelet插件通过将多个节点的功能集成到一个进程中，可以 减少节点间的通信开销，提高系统的性能，这对于传输图像和点云特别有用。 "
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBmsckf_vio\fP"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 S-MSCKF注释 的 源代码自动生成\&.
