.TH "/home/speike/VSLAM/MSCKF_vio_ws/src/MSCKF_comments/test/math_utils_test.cpp" 3 "2024年 五月 9日 星期四" "S-MSCKF注释" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/speike/VSLAM/MSCKF_vio_ws/src/MSCKF_comments/test/math_utils_test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <Eigen/Dense>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <msckf_vio/math_utils\&.hpp>\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "\fBTEST\fP (MathUtilsTest, skewSymmetric)"
.br
.ti -1c
.RI "\fBTEST\fP (MathUtilsTest, quaternionNormalize)"
.br
.ti -1c
.RI "\fBTEST\fP (MathUtilsTest, quaternionToRotation)"
.br
.ti -1c
.RI "\fBTEST\fP (MathUtilsTest, rotationToQuaternion)"
.br
.ti -1c
.RI "\fBTEST\fP (MathUtilsTest, quaternionMultiplication)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "函数说明"
.PP 
.SS "int main (int argc, char ** argv)"

.SS "TEST (MathUtilsTest, quaternionMultiplication)"

.SS "TEST (MathUtilsTest, quaternionNormalize)"

.SS "TEST (MathUtilsTest, quaternionToRotation)"

.SS "TEST (MathUtilsTest, rotationToQuaternion)"

.SS "TEST (MathUtilsTest, skewSymmetric)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 S-MSCKF注释 的 源代码自动生成\&.
