.TH "/home/speike/VSLAM/MSCKF_vio_ws/src/MSCKF_comments/src/msckf_vio.cpp" 3 "2024年 五月 9日 星期四" "S-MSCKF注释" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/speike/VSLAM/MSCKF_vio_ws/src/MSCKF_comments/src/msckf_vio.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <Eigen/SVD>\fP
.br
\fC#include <Eigen/QR>\fP
.br
\fC#include <Eigen/SparseCore>\fP
.br
\fC#include <Eigen/SPQRSupport>\fP
.br
\fC#include <boost/math/distributions/chi_squared\&.hpp>\fP
.br
\fC#include <eigen_conversions/eigen_msg\&.h>\fP
.br
\fC#include <tf_conversions/tf_eigen\&.h>\fP
.br
\fC#include <sensor_msgs/PointCloud2\&.h>\fP
.br
\fC#include <pcl_ros/point_cloud\&.h>\fP
.br
\fC#include <pcl/point_types\&.h>\fP
.br
\fC#include <msckf_vio/msckf_vio\&.h>\fP
.br
\fC#include <msckf_vio/math_utils\&.hpp>\fP
.br
\fC#include <msckf_vio/utils\&.h>\fP
.br

.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBmsckf_vio\fP"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 S-MSCKF注释 的 源代码自动生成\&.
