.TH "msckf_vio::ImageProcessor::FeatureMetaData" 3 "2024年 五月 9日 星期四" "S-MSCKF注释" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msckf_vio::ImageProcessor::FeatureMetaData \- \fBFeatureMetaData\fP Contains necessary information of a feature for easy access\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBFeatureIDType\fP \fBid\fP"
.br
.ti -1c
.RI "float \fBresponse\fP"
.br
.ti -1c
.RI "int \fBlifetime\fP"
.br
.ti -1c
.RI "cv::Point2f \fBcam0_point\fP"
.br
.ti -1c
.RI "cv::Point2f \fBcam1_point\fP"
.br
.in -1c
.SH "详细描述"
.PP 
\fBFeatureMetaData\fP Contains necessary information of a feature for easy access\&. 
.SH "类成员变量说明"
.PP 
.SS "cv::Point2f msckf_vio::ImageProcessor::FeatureMetaData::cam0_point"

.SS "cv::Point2f msckf_vio::ImageProcessor::FeatureMetaData::cam1_point"

.SS "\fBFeatureIDType\fP msckf_vio::ImageProcessor::FeatureMetaData::id"

.SS "int msckf_vio::ImageProcessor::FeatureMetaData::lifetime"

.SS "float msckf_vio::ImageProcessor::FeatureMetaData::response"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S-MSCKF注释 的 源代码自动生成\&.
