.TH "msckf_vio::ImageProcessor::ProcessorConfig" 3 "2024年 五月 9日 星期四" "S-MSCKF注释" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msckf_vio::ImageProcessor::ProcessorConfig \- \fBProcessorConfig\fP Configuration parameters for feature detection and tracking\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "int \fBgrid_row\fP"
.br
.ti -1c
.RI "int \fBgrid_col\fP"
.br
.ti -1c
.RI "int \fBgrid_min_feature_num\fP"
.br
.ti -1c
.RI "int \fBgrid_max_feature_num\fP"
.br
.ti -1c
.RI "int \fBpyramid_levels\fP"
.br
.ti -1c
.RI "int \fBpatch_size\fP"
.br
.ti -1c
.RI "int \fBfast_threshold\fP"
.br
.ti -1c
.RI "int \fBmax_iteration\fP"
.br
.ti -1c
.RI "double \fBtrack_precision\fP"
.br
.ti -1c
.RI "double \fBransac_threshold\fP"
.br
.ti -1c
.RI "double \fBstereo_threshold\fP"
.br
.in -1c
.SH "详细描述"
.PP 
\fBProcessorConfig\fP Configuration parameters for feature detection and tracking\&. 
.SH "类成员变量说明"
.PP 
.SS "int msckf_vio::ImageProcessor::ProcessorConfig::fast_threshold"

.SS "int msckf_vio::ImageProcessor::ProcessorConfig::grid_col"

.SS "int msckf_vio::ImageProcessor::ProcessorConfig::grid_max_feature_num"

.SS "int msckf_vio::ImageProcessor::ProcessorConfig::grid_min_feature_num"

.SS "int msckf_vio::ImageProcessor::ProcessorConfig::grid_row"

.SS "int msckf_vio::ImageProcessor::ProcessorConfig::max_iteration"

.SS "int msckf_vio::ImageProcessor::ProcessorConfig::patch_size"

.SS "int msckf_vio::ImageProcessor::ProcessorConfig::pyramid_levels"

.SS "double msckf_vio::ImageProcessor::ProcessorConfig::ransac_threshold"

.SS "double msckf_vio::ImageProcessor::ProcessorConfig::stereo_threshold"

.SS "double msckf_vio::ImageProcessor::ProcessorConfig::track_precision"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S-MSCKF注释 的 源代码自动生成\&.
