.TH "/home/speike/VSLAM/MSCKF_vio_ws/src/MSCKF_comments/include/msckf_vio/utils.h" 3 "2024年 五月 9日 星期四" "S-MSCKF注释" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/speike/VSLAM/MSCKF_vio_ws/src/MSCKF_comments/include/msckf_vio/utils.h
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <opencv2/core/core\&.hpp>\fP
.br
\fC#include <Eigen/Geometry>\fP
.br

.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBmsckf_vio\fP"
.br
.ti -1c
.RI " \fBmsckf_vio::utils\fP"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "Eigen::Isometry3d \fBmsckf_vio::utils::getTransformEigen\fP (const ros::NodeHandle &nh, const std::string &field)"
.br
.ti -1c
.RI "cv::Mat \fBmsckf_vio::utils::getTransformCV\fP (const ros::NodeHandle &nh, const std::string &field)"
.br
.ti -1c
.RI "cv::Mat \fBmsckf_vio::utils::getVec16Transform\fP (const ros::NodeHandle &nh, const std::string &field)"
.br
.ti -1c
.RI "cv::Mat \fBmsckf_vio::utils::getKalibrStyleTransform\fP (const ros::NodeHandle &nh, const std::string &field)"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 S-MSCKF注释 的 源代码自动生成\&.
